### PR TITLE
Fixing #20 Updating Modules section

### PR DESCRIPTION
**Pull request by claughlin-r7**
Adding details to modules section to use require/modules.export when developing in node.

### CODE REVIEW

**Comment by tquetano-r7** [comment]
Is this still active?

**Comment by claughlin-r7** [comment]
Yeah forgot about this, I'll make the changes today

**Comment by claughlin-r7** [comment]
Thing I addressed the changes. Let me know if your happy and I can merge

**Comment by claughlin-r7** [comment]
@tquetano-r7 can you have a look over this again

**Pull request merged**
